
// 所有三级权限及更多枚举值
export enum Powers {
  orderQuery = 'jygl.rsgdd', // 认申购订单
  orderQueryProxy = 'jygl.rsgdd.dx', // 认申购订单 -- 代销
  orderQueryDirect = 'jygl.rsgdd.zx', // 认申购订单 -- 直销
  orderQueryRedeem = 'jygl.shdd', // 赎回订单
  orderQueryRedeemProxy = 'jygl.shdd.dx', // 赎回订单 -- 代销
  orderQueryRedeemDirect = 'jygl.shdd.zx', // 赎回订单 -- 直销
  overseaAndInsuranceOrderList = 'jygl.hwbxdd', // 海外/保险订单
  editProduct = 'cpgl.cpk.bjcp', // 产品管理编辑
  viewProduct = 'cpgl.cpk.ckcp', // 查看产品,
  addNetValue = 'cpgl.cpjzgl.tj', // 产品添加净值
  userApplySales = 'cltj.yhsqlb.lcsck', // 用户申请列表--理财师数据
  userApplyNoSales = 'cltj.yhsqlb.yyck', // 用户申请列表--运营数据
  downloadNetValueTemplate = 'cpgl.cpjzgl.xzjzmb', // 产品下载净值模板
  importNetValue = 'cpgl.cpjzgl.dr', // 产品导入净值
  sysDelUser = 'xtgl.zzjg.scyg', // 系统管理组织结构删除员工
  sysAddUser = 'xtgl.zzjg.tjyg', // 系统管理组织结构添加员工
  sysEditUser = 'xtgl.zzjg.bjyg', // 系统管理组织结构编辑员工
  sysSetRole = 'xtgl.zzjg.szjs', // 系统管理组织结构设置角色
  sysResetPwd = 'xtgl.zzjg.czmm', // 系统管理组织结构重置密码
  sysRoleListAdd = 'xtgl.jsgl.tjjs', // 系统管理角色管理添加角色
  sysRoleListEdit = 'xtgl.jsgl.bjjs', // 系统管理角色管理编辑角色
  sysRoleListDel = 'xtgl.jsgl.scjs', // 系统管理角色管理删除角色
  sysRoleListView = 'xtgl.jsgl.ckjs', // 系统管理角色管理查看角色
  sysPowerListSave = 'xtgl.jssq.sq', // 角色授权保存
  sysArgAdd = 'xtgl.sjzd.tjzd', // 数据字典添加
  sysArgEdit = 'xtgl.sjzd.bjzd', // 数据字典编辑
  sysArgDel = 'xtgl.sjzd.sczd', // 数据字典删除
  sysCalendarAdd = 'xtgl.gzrlsz.tj', // 工作日历添加
  sysCalendarAddByYear = 'xtgl.gzrlsz.antj', // 工作日历按年添加
  sysCalendarEdit = 'xtgl.gzrlsz.bj', // 工作日历编辑
  sysCalendarDel = 'xtgl.gzrlsz.sc', // 工作日历删除
  sysCalendarView = 'xtgl.gzrlsz.ckrl', // 工作日历查看日历
  activityCreate = 'nrgl.hdgl.xjhd', // 新建活动
  activityPicEdit = 'nrgl.hdgl.bjym', // 编辑活动页面
  activityOp = 'nrgl.hdgl.hdsxx', // 活动上下线操作
  activityDel = 'nrgl.hdgl.schd', // 删除活动
  redeemApplyAudit = 'jygl.shsqsh.sh', // 赎回申请审核
  redeemApplyExport = 'jygl.shsqsh.dc', // 赎回导出数据
  startBooking = 'yygl.qdbd.qdrgyy', // 启动认购
  startBuy = 'yygl.qdbd.qdsgyy', // 启动申购
  startHistory = 'yygl.qdbd.qdlsgl', // 启动历史
  declarationAudit = 'yygl.bdsh.sh', // 报单审核
  declarationCheck = 'yygl.wdbd.ckyy', // 报单查看
  allDeclarationCheck = 'yygl.qbbd.ckyy', // 全部报单,
  consumerVisitAdd = 'khgl.khbf.tjbfrz', // 添加拜访日志
  consumerVisitDel = 'khgl.khbf.scbfrz', // 删除拜访日志
  consumerVisitEdit = 'khgl.khbf.bjbfrz', // 编辑拜访日志
  tradeVisitEdit = 'kfgl.ljqhfxx.hf', // 客服冷静期回访
  gimsCallback = 'khgl.khlb.gimshs', // 客戶列表 -- 回收
  gimsAllocate = 'khgl.khlb.gimsfp', // 客戶列表 -- 分配
  gimsConsumerCheck = 'khgl.khlb.ck', // 客戶列表 -- 查看
  gimsConsumerEdit = 'khgl.khlb.bjkh', // 客戶列表 -- 编辑
  reportCheck = 'cpgl.cpk.ckcp.thbg', // 客戶列表 -- 投后报告
  consumerCompareCheck = 'khgl.khgsjy.ck', // 客户归属校验 -- 查看
  consumerCompareUpdate = 'khgl.khgsjy.gx', // 客户归属校验 -- 更新
  consumerCompareGims = 'khgl.khgsjy.gimsyz', // 客户归属校验 -- 与GIMS一致
  consumerCompareNewSystem = 'khgl.khgsjy.xxtyz', // 客户归属校验 -- 与新系统一致
  followConsumerCheck = 'khgl.khgjqk.ck', // 客户跟进列表 -- 查看
  followConsumerAllocate = 'khgl.khgjqk.zfp', // 客户跟进列表 -- 转分配
  noAssignConsumerCheck = 'khgl.dfpkhlb.ck', // 待分配客户列表 -- 查看
  noAssignConsumerAllocate = 'khgl.dfpkhlb.fp', // 待分配客户列表 -- 分配
}
